-- require("settings.plugins.nvim_tree")
require("settings.plugins.lualine")
require("settings.plugins.gitsigns")
require("settings.plugins.treesitter")
require("settings.plugins.terminal")
require("settings.plugins.notify")
require("settings.plugins.leap")
require("settings.plugins.which_key")
require("settings.keymaps")
