require("settings.plugins.nvim_tree")
require("settings.plugins.lualine")
require("settings.plugins.gitsigns")
require("settings.plugins.telescope")
require("settings.plugins.treesitter")
require("settings.plugins.terminal")
require("settings.plugins.notify")
require("settings.plugins.leap")
