require("settings.keymaps.general")
require("settings.keymaps.split")
require("settings.keymaps.tabs")
require("settings.keymaps.todo")
require("settings.keymaps.git")
require("settings.keymaps.movement")
require("settings.keymaps.lsp")
require("settings.keymaps.buffers")
