vim.keymap.set("n", "<leader>tc", ":tabclose<CR>", { desc = "List all TODO in telescope", silent = true })
vim.keymap.set("n", "<leader>tn", ":tabnew %<CR>", { desc = "Open File in new tab", silent = true })
vim.keymap.set("n", "t", function()
  vim.cmd(":tabn " .. vim.v.count1)
end, { desc = "Go to tab with v:count1", silent = true })
